### ISSUE TITLE
Adding the possibility to choose the UMLS base URI

### ISSUE THREAD

**Issue by vemonet** [ncbo/umls2rdf#12]
Hi, this is a proposition of slight enhancement: to be able to choose the base URI of the URI pointing to UMLS semantic type (umls:hasSTY property)

For the moment it is http://purl.bioontology.org/ontology/, but it could be interesting to point to another URI, in particular to link to Semantic type in another language (if we have the UMLS ontology in another language than English, it could be interesting to point to a UMLS Semantic type in this language)

The modification would be really small:
Adding the following to conf_sample.py (it will still be the bioontology.org base URI by default)
```UMLS_BASE_URI = "http://purl.bioontology.org/ontology/"```

And changing the get_umls_url function in umls2rdf.py
```
def get_umls_url(code):
    return "%s%s/"%(conf.UMLS_BASE_URI,code)
```

**Comment by msalvadores** [comment]
@vemonet I will look at it in the next couple of weeks but if you want to implement it yourself we accept pull requests. It seems you have done some initial research and you could implement this change.

Let me know if you want to give it a go.

Thanks for reporting this.

**Comment by jonquet** [comment]
@vemonet Vincent, what is the status for this now. It's done now, no?

**Comment by msalvadores** [comment]
Yep. This was  merged. I am closing this issue.
