### ISSUE TITLE
questions about the UMLS 2 RDF script

### ISSUE THREAD

**Issue by zaihrayeu** [ncbo/umls2rdf#17]
hi everyone, 

I came across this project and I found it very interesting.  there are a couple of questions I would like to ask :
1. in the prefLabel computation code, you filter by the MRCONSO_ISPREF attribute, if there are no atoms returned, you return the string of the first atom in the whole list. This line:
   https://github.com/ncbo/umls2rdf/blob/master/umls2rdf.py#L276

Question: why at this point you do not check for atoms whose type starts from ‘P’:
https://github.com/ncbo/umls2rdf/blob/master/umls2rdf.py#L286 
1. in some parts of the flow, you compute prefLabel as terms whose type started from ‘P’ (as above) or contains ‘P’:
   https://github.com/ncbo/umls2rdf/blob/master/umls2rdf.py#L299

what is the rationale behind this logic?
1. both concepts and semantic types are modelled as owl:class with no differentiation between them. The only way to understand that a class is a semantic type class is to see if it appears as the target for the hasSty object property relation. Was there any specific reason behind this decision? Is there any other way to say that a certain owl class represents a UMLS concept or a semantic type?
2. Some of the RDF outputs produced by the script contain incorrect merged concepts, based on the load_on_code parameter strategy: e.g.: TCGA  in NCI. We think that this might be related to incorrect data created by UMLS. Have you experienced this issue and, if yes, have you any thoughts about possible improvements/workarounds in the umls2rdf script? The first idea that came into our minds is: explicitly exclude TCGA concepts from NCI conversion

thanks in advance
Ilya

**Comment by msalvadores** [comment]
@zaihrayeu thanks for your questions.

> Question: why at this point you do not check for atoms whose type starts from ‘P’:

From what I remember. `MRCONSO_ISPREF` and `MRCONSO_TTY` align and there was not a case in which the first character or `MRCONSO_TTY` would help to disambiguate when there is not `MRCONSO_ISPREF` set to yes. If you find an example that contradicts this please let us know and I will look at it. That logic to select the pref label was tuned with a subset of ontologies that we use in BioPortal and it might not be complete.

> both concepts and semantic types are modelled as owl:class with no differentiation between them. The only way to understand that a class is a semantic type class is to see if it appears as the target for the hasSty object property relation. Was there any specific reason behind this decision? 

We considered Semantic Types as an ontology as well (see http://bioportal.bioontology.org/ontologies/STY) so we decided to model them as classes. That way we can publish them in BioPortal.

> Is there any other way to say that a certain owl class represents a UMLS concept or a semantic type?

I think I'd use the hasSTY too but can also traverse the STY tree from the roots to gather all STYs classes easily.

> Some of the RDF outputs produced by the script contain incorrect merged concepts, based on the load_on_code parameter strategy: e.g.: TCGA in NCI. We think that this might be related to incorrect data created by UMLS. Have you experienced this issue and, if yes, have you any thoughts about possible improvements/workarounds in the umls2rdf script? The first idea that came into our minds is: explicitly exclude TCGA concepts from NCI conversion

No. We have not seen that. We use `rapper` to parse and validate the RDF with no issues. Though I am not whether NCI is one of the ontologies that we dump and parse in BioPortal. If you post some of those errors maybe we can help.

**Comment by jvendetti** [comment]
@zaihrayeu, @msalvadores - by NCI, I assume you mean the National Cancer Institute Thesaurus located [here](http://bioportal.bioontology.org/ontologies/NCIT)?  This is not one of the ontologies that's processed by the umls2rdf script.  The NCIT ontology maintainer has specified a pull location in BioPortal for the ontology source file (in OWL format).

**Comment by zaihrayeu** [comment]
@msalvadores, @jvendetti : thanks for your feedback, it was very useful. one last question, could you please comment on this: in some parts of the flow, you compute prefLabel as terms whose type started from ‘P’ (as above) or contains ‘P’: https://github.com/ncbo/umls2rdf/blob/master/umls2rdf.py#L299
what is the rationale behind this logic?

about NCI: it is in the mysql umls dump, but not in the mls.conf config file used in importing. as I understand, the reason is that the dataset is already available in the owl format.

**Comment by jvendetti** [comment]
@zaihrayeu: regarding NCIT, that's correct.  The ontology maintainers publish the NCIT source file (in OWL format) to an FTP location.  The BioPortal application checks that location nightly for new versions.
