### ISSUE TITLE
Loading on CODE vs on CUI

### ISSUE THREAD

**Issue by zaihrayeu** [ncbo/umls2rdf#18]
hi everyone,

I am wondering why certain sources are loaded on codes and some are loaded on CUIs. as I understand, codes are provided by the source whereas CUIs are provided by UMLS. is it a matter of trusting more the original source or UMLS on how to aggregate classes?

I found some examples where labels with the same code and different CUIs represent different things, e.g., "cancers" and "AIDS" or "urine" and "urinary aspects".

I computed some stats on the number of codes linked to distinct CUIs in different datasets (see attached screenshots), and it looks like the problem is pretty persistent, especially in MSH and CPT datasets.

thanks in advance for your feedback

regards
Ilya

![screen shot 2016-11-07 at 16 06 20](https://cloud.githubusercontent.com/assets/22833710/20065229/49ed8ede-a505-11e6-900c-ea378db0e5e5.png)
![screen shot 2016-11-07 at 16 06 54](https://cloud.githubusercontent.com/assets/22833710/20065232/49f53332-a505-11e6-83da-e2defadc186d.png)
<img width="269" alt="screen shot 2016-11-07 at 16 07 16" src="https://cloud.githubusercontent.com/assets/22833710/20065231/49f1ecf4-a505-11e6-8465-36f11c8df418.png">
<img width="278" alt="screen shot 2016-11-07 at 16 07 24" src="https://cloud.githubusercontent.com/assets/22833710/20065230/49ef2f14-a505-11e6-81fb-1d20032e465a.png">

**Comment by msalvadores** [comment]
> I am wondering why certain sources are loaded on codes and some are loaded on CUIs. as I understand, codes are provided by the source whereas CUIs are provided by UMLS. is it a matter of trusting more the original source or UMLS on how to aggregate classes?

Some source hierarchies break with the CUI mappings and for those is better to use the original code hierarchies. I believe that is the main reason.

> I found some examples where labels with the same code and different CUIs represent different things, e.g., "cancers" and "AIDS" or "urine" and "urinary aspects".

That is dependent on each source. For your example with MESH ... MESH is designed for document indexing and the particular concept you are looking at is a qualifier. The way it reads in [1] is that `urine` is a qualifier that can be applied to the concepts `urinary levels` and `urinary aspects`. UMLS often looses the semantics of these relations. These can be buried in MRREL or you have to track them back to the original source.

[1] https://id.nlm.nih.gov/mesh/Q000652.html

> I computed some stats on the number of codes linked to distinct CUIs in different datasets (see attached screenshots), and it looks like the problem is pretty persistent, especially in MSH and CPT datasets.

Following up from my previous comment. MESH has several relations between topical descriptors, concepts and qualifiers that get lost in UMLS. You might find them in MRREL but I am not certain about this. CPT is a coding terminology and sometimes they add synonyms based on what they can bill for a certain code, that does not mean that all of those are equivalent in the purest of the synonym ... it means that for CPT all of those can be used equivalently for billing purposes.

I hope this makes sense. Please close if it is answered.

**Comment by zaihrayeu** [comment]
@msalvadores , thanks a lot for your answers. it makes total sense. closing the issue
