### ISSUE TITLE
Wrong generation of literals

### ISSUE THREAD

**Issue by vemonet** [ncbo/umls2rdf#20]
The script generates wrong literals for all ontologies. Instead of being surrounded by one quote, all literals are surrounded by 3 quotes.
And parsing the TTL with OWLAPI meet an error (but it worked with Jena) : 

> Parser: TurtleOntologyParser
> uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered " "\"" "\"^^xsd:string ;\n\t<http://purl.bioontology.org/ontology/MESH/AQL> \" "" at line 54034, column 141.
> Was expecting:
>     "." ...

The line causing the error is the following:

>   <http://purl.bioontology.org/ontology/MESH/AN> """Jaffe-Lichtenstein usually goes here but check text for possible \"polyostotic\""""^^xsd:string ;

[Relevant xkcd](https://xkcd.com/1638/)

**Comment by alexskr** [comment]
Turtle format allows triple quotes for long literals that may contain linebreaks.
