### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by safrant** [ncbo/umls2rdf#22]
When I run this using python 2.7.10 I get an error on the MySQLdb import. The MySQLdb import is no longer supported by python.  What python version is this intended to run under, and is there any work on updating this to a more recent version?  

$ python umls2rdf.py 
Traceback (most recent call last):
  File "umls2rdf.py", line 11, in <module>
    import MySQLdb
ImportError: No module named MySQLdb

**Comment by jvendetti** [comment]
@alexskr - do you happen to recall what version of Python was used the last time this script was run internally?

**Comment by alexskr** [comment]
I believe we used  2.7.6 but mysql module should be available in 2.7.10 just run something like "pip install MySQL-python"

**Comment by safrant** [comment]
Thanks.  I was able to cram MySQLdb onto my system using "sudo easy_install MySQL-python".  I can now run the script but am working on how to customize it for my situation - extracting ICD-0-3 into turtle.
