### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by rwynne** [ncbo/umls2rdf#24]
Hi all,

This is working great!  I'm using Windows 10, and found the script didn't work out-of-the-box with python3.

I downgraded to 2.7.15 and it worked like a charm.  Also, for the MySQLdb module I needed to use an executable for install, as 'python -m pip install MySQLdb' failed.  MySQL-python-1.2.3.win-amd64-py2.7 seemed to did the trick (http://www.codegood.com/archives/129).  For the MetaMorphosys load portion, I found MySQL 5.5 to be best due to NLM disclaimers of 5.6 and higher.

Should these possible requirements/procedures be documented in the README?

Thanks again!

**Comment by jvendetti** [comment]
@rwynne - thank you for the feedback! I agree that this information would be useful to have in the README if anyone else on a Windows system attempts to use. You're welcome to add it yourself and submit a pull request. Otherwise, we'll try to get to it when we have time.

**Comment by rwynne** [comment]
@jvendetti Pull request sent. Please feel free to correct any formatting, grammar, etc.  Thanks!

**Comment by jvendetti** [comment]
@rwynne - pull request merged. Many thanks for the contribution!
