### ISSUE TITLE
Incorrect encoding introduced during UMLS import

### ISSUE THREAD

**Issue by mdorf** [ncbo/umls2rdf#28]
http://bioportal.bioontology.org/ontologies/ICD9CM/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FICD9CM%2F386.00&jump_to_nav=true 

Per user feedback:

Name: Nicolas Joannin
Email: nicolas.joannin@linguamatics.com
Location: https%3A%2F%2Fbioportal.bioontology.org%2Fontologies%2FICD9CM
Feedback:

Encoding problems with your ICD9CM and ICD10CM TTL files:

Hello,

The files you provide for ICD9CM and ICD10CM have erroneous characters, e.g. "MÃ©niÃ¨re's disease" instead of "Ménière's disease".

This type of character replacement is typical when a UTF-8 encoded source file is read as a Windows-1252 encoded file (probably the default encoding of the machine used to process the data).

I would suggest that when next updating these files you consider updating your script to read the source data with the proper encoding.

Cheers, 
Nicolas

**Comment by graybeal** [comment]
oops, didn't mean to close

**Comment by alexskr** [comment]
this would be fixed once we finalize UMLS 2018AB release

**Comment by alexskr** [comment]
fixed

**Comment by mdorf** [comment]
This issue appears to be back in the UMLS 2019AA release. The original ontology (ICD9CM) is affected, as well as at least one other ontology (SCTSPA - the Spanish version of SNOMED CT), as referenced by a user on the support list.

http://bioportal.bioontology.org/ontologies/ICD9CM/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FICD9CM%2F386.00&jump_to_nav=true

http://bioportal.bioontology.org/ontologies/SCTSPA/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSCTSPA%2F78621006

Relevant support list issues:
http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-Nicolas-Joannin-td4656746.html#a4656757

http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-Ryan-Whaley-td4657443.html

**Comment by alexskr** [comment]
Fixed in 2019AB release
