### ISSUE TITLE
mysqlclient instead of MySQLdb?

### ISSUE THREAD

**Issue by turbomam** [ncbo/umls2rdf#33]
I seem to thrash on `MySQLdb` every time I need to install or reinstall `umls2rdf`. I just got it running again on a Mac OS Catalina system with homebrew-based MySQL after installing `mysqlclient` with pip. I think I may have done the same thing in Ubuntu Linux systems.

Have you heard anything like this before? If I can document my case better, would you add it to the `README`?

**Comment by graybeal** [comment]
Good question and nice idea, thanks! If you are able to post your command sequence it would at least be documented here, where we could refer to it.  We have some tension about documenting how to do everything else that we don't develop—ideally this could be documented on a MySQL site, and we could point to it.

**Comment by alexskr** [comment]
MySQLdb library has been switched to PyMySQL library in 
https://github.com/ncbo/umls2rdf/pull/36 and https://github.com/ncbo/umls2rdf/commit/8d9f98a8ba2feed98c8c8667422c880349e853b0
this should make installation a bit easier
