### ISSUE TITLE
Questions about umls2rdf 

### ISSUE THREAD

**Issue by bbartley** [ncbo/umls2rdf#37]
Hi, I'm potentially interested in using UMLS in a linked-data format for the NIH's Bridge2AI program.  As I have not worked much with UMLS before, I have some naive questions:

1). Why is it necessary to convert the ontologies in UMLS into RDF?  Aren't the ontologies already natively defined in OWL/OBO?
2). Are the UMLS CUIs preserved in the translation?
3). Are synonyms from the UMLS Metathesaurus preserved in the translation?

Thanks for taking the time to answer my questions!

**Comment by graybeal** [comment]
1) No, they aren't. :-(  See the NCBI Metathesaurus site for details about the format.
2) Yes. Visit any class of any UMLS ontology in BioPortal (use the Classes tab and choose a class from the tree view on the left) to see the annotations for that class.
3) Yes, they should be. There may be some ontologies where the original relationships weren't picked up appropriately by the UMLS mappings. But I haven't heard any complaints about that.
