### ISSUE TITLE
E with acute accent generated incorrectly in ICD10CM TTL file

### ISSUE THREAD

**Issue by jvendetti** [ncbo/umls2rdf#45]
From a user on the BioPortal support list:

> In ICD10CM the é characters are displaying incorrectly e.g.:
https://bioportal.bioontology.org/ontologies/ICD10CM?p=classes&conceptid=C84.1

This is a link to the class in the UMLS Metathesaurs browser:

https://uts.nlm.nih.gov/uts/umls/vocabulary/ICD10CM/C84.1

... where the name of the class is listed as "Sézary disease".

This is the same class in the ICD10CM TTL file generated by this program:

```
<http://purl.bioontology.org/ontology/ICD10CM/C84.1> a owl:Class ;
	skos:prefLabel """SÃ©zary disease"""@en ;
	skos:notation """C84.1"""^^xsd:string ;
	rdfs:subClassOf <http://purl.bioontology.org/ontology/ICD10CM/C84> ;
	<http://purl.bioontology.org/ontology/ICD10CM/ORDER_NO> """02478"""^^xsd:string ;
	umls:cui """C0036920"""^^xsd:string ;
	umls:tui """T191"""^^xsd:string ;
	umls:hasSTY <http://purl.bioontology.org/ontology/STY/T191> ;
```

The e with acute accent in the `skos:prefLabel` is incorrect.

**Comment by justin2004** [comment]
@jvendetti 

have you enabled UTF-8 in your environment?
e.g. in a debian based distro:
https://github.com/SPARQL-Anything/sparql.anything/blob/v1.0-DEV/Dockerfile.development#L11-L16

**Comment by alexskr** [comment]
we set it to `en_US.UTF-8` on the os level

**Comment by justin2004** [comment]
@alexskr 
just wanted to note that on a linux distro it isn't enough to set the environment variables. you also need to have the locales installed. the dockerfile i referenced does that.

**Comment by alexskr** [comment]
The MySQL database was created without the proper UTF8 character set.  This issue will be resolved after umls2024aa is loaded into BioPortal.
